# Generated by Django 5.1.1 on 2024-12-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_full_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='Nome Completo'),
        ),
    ]
