# Generated by Django 5.1.1 on 2024-12-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('descricao_evento', models.TextField()),
                ('imagem_evento', models.ImageField(upload_to='eventos/')),
                ('preco_ingresso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_ingresso', models.PositiveIntegerField()),
                ('data_criacao_evento', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
            ],
        ),
    ]
