# Generated by Django 5.1.1 on 2024-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('acessórios', 'Acessórios')], max_length=10, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
